server.port=8080
app.name=ShopWave

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# PostgreSQL Datasource (direct connection without Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/shopwave
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=12345678
# HikariCP connection pool settings (optional but recommended)
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10